apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secrets" (include "mysql.fullname" .) }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | b64enc }}
{{- end }}
