apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
  selector:
    app.kubernetes.io/name: {{ include "mysql.name" . }}
  clusterIP: None
