apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todoapp.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "todoapp.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "todoapp.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "todoapp.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ include "todoapp.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          env:
{{- $secretName := printf "%s-secrets" (include "todoapp.fullname" .) }}
{{- range $k, $v := .Values.secrets }}
            - name: {{ $k }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $k }}
{{- end }}
          volumeMounts:
            - mountPath: /data
              name: todoapp-storage
      volumes:
        - name: todoapp-storage
          persistentVolumeClaim:
            claimName: {{ printf "%s-pvc" (include "todoapp.fullname" .) }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.nodeAffinity.key }}
                    operator: In
                    values:
{{- range .Values.nodeAffinity.values }}
                      - "{{ . }}"
{{- end }}
