apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
spec:
  capacity:
    storage: {{ .Values.pv.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/{{ .Values.pv.name }}
  {{- if .Values.pv.storageClassName }}
  storageClassName: {{ .Values.pv.storageClassName }}
  {{- end }}
