apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todoapp.fullname" . }}
  labels:
    app: {{ include "todoapp.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "todoapp.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "todoapp.fullname" . }}
    spec:
      serviceAccountName: {{ include "todoapp.serviceAccountName" . }}
      containers:
        - name: todoapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.userKey }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.passwordKey }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.nameKey }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
