apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "todoapp.fullname" . }}-pvc
spec:
  accessModes:
{{- range .Values.pvc.accessModes }}
    - {{ . }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.requests.storage }}
